/**
 * NGSS 9-12 Science Standards Comprehensive Database
 * High School Next Generation Science Standards (Physical Science, Earth & Space, Life Science, Engineering)
 */

const NGSS_STANDARDS_DATA = [
    // --- PHYSICAL SCIENCE: FORCES & MOTION (HS-PS2) ---
    {
        code: "HS-PS2-1",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Forces and Motion",
        title: "Newton's Second Law of Motion",
        pe: "Analyze data to support the claim that Newton's second law of motion describes the mathematical relationship among the net force on a macroscopic object, its mass, and its acceleration.",
        clarification: "Examples of data could include tables or graphs of position or velocity as a function of time for objects subjected to a net force.",
        boundary: "Assessment is limited to one-dimensional motion, with constant forces.",
        sep: "Analyzing and Interpreting Data",
        dci: "PS2.A: Forces and Motion",
        ccc: "Cause and Effect",
        unitLink: "../unit1-dashboard.html",
        keywords: ["force", "mass", "acceleration", "newton", "motion", "f=ma", "kinematics", "data"]
    },
    {
        code: "HS-PS2-2",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Forces and Motion",
        title: "Conservation of Linear Momentum",
        pe: "Use mathematical representations to support the claim that the total momentum of a system of objects is conserved when there is no net force on the system.",
        clarification: "Emphasis is on the quantitative analysis of system momentum before and after interaction in one dimension.",
        boundary: "Assessment is limited to system collisions in one dimension.",
        sep: "Using Mathematics and Computational Thinking",
        dci: "PS2.A: Forces and Motion",
        ccc: "Systems and System Models",
        unitLink: "../unit4-dashboard.html",
        keywords: ["momentum", "conservation", "collision", "impulse", "mass", "velocity", "p=mv"]
    },
    {
        code: "HS-PS2-3",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Forces and Motion",
        title: "Collision & Impact Engineering Design",
        pe: "Apply scientific and engineering ideas to design, evaluate, and refine a device that minimizes the force on a macroscopic object during a collision.",
        clarification: "Examples of devices could include football helmets, air bags, car crumple zones, or egg drop padding.",
        boundary: "Assessment is limited to qualitative evaluations and relative comparisons.",
        sep: "Constructing Explanations and Designing Solutions",
        dci: "PS2.A: Forces and Motion",
        ccc: "Cause and Effect",
        unitLink: "../unit4-dashboard.html",
        keywords: ["collision", "engineering", "impulse", "crumple zone", "safety", "egg drop", "force reduction"]
    },
    {
        code: "HS-PS2-4",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Forces and Motion",
        title: "Newton's Law of Gravitation & Coulomb's Law",
        pe: "Use mathematical representations of Newton's Law of Gravitation and Coulomb's Law to describe and predict the gravitational and electrostatic forces between objects.",
        clarification: "Emphasis is on the inverse-square law behavior for attraction and repulsion.",
        boundary: "Assessment is limited to simple systems with two point charges or masses.",
        sep: "Using Mathematics and Computational Thinking",
        dci: "PS2.B: Types of Interactions",
        ccc: "Patterns",
        unitLink: "../Unit_7_Electricity_and_Magnetism/Unit_7_Outline.md",
        keywords: ["gravity", "coulomb", "electrostatic", "inverse square", "force", "charge", "mass"]
    },
    {
        code: "HS-PS2-5",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Forces and Motion",
        title: "Electric Current and Magnetic Fields",
        pe: "Plan and conduct an investigation to provide evidence that an electric current can produce a magnetic field and that a changing magnetic field can produce an electric current.",
        clarification: "Emphasis is on qualitative observations of electromagnets, generators, and induction coils.",
        boundary: "Assessment does not include quantitative calculations of magnetic flux or field vectors.",
        sep: "Planning and Carrying Out Investigations",
        dci: "PS2.B: Types of Interactions",
        ccc: "Cause and Effect",
        unitLink: "../unit7-dashboard.html",
        keywords: ["electromagnetism", "magnetic field", "induction", "faraday", "current", "coil", "generator"]
    },

    // --- PHYSICAL SCIENCE: ENERGY (HS-PS3) ---
    {
        code: "HS-PS3-1",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Energy",
        title: "Conservation of Energy & Energy Transformations",
        pe: "Create a computational model or mathematical representation to calculate the change in the energy of one component in a system when the change in energy of the other component(s) and energy flows in and out of the system are known.",
        clarification: "Emphasis is on kinetic, potential, thermal, and chemical energy transformations.",
        boundary: "Assessment is limited to basic algebraic expressions and simple closed/open systems.",
        sep: "Using Mathematics and Computational Thinking",
        dci: "PS3.A: Definitions of Energy",
        ccc: "Energy and Matter",
        unitLink: "../unit5-dashboard.html",
        keywords: ["conservation of energy", "kinetic energy", "potential energy", "thermal energy", "work", "joules"]
    },
    {
        code: "HS-PS3-2",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Energy",
        title: "Macroscopic & Microscopic Energy Models",
        pe: "Develop and use a model to illustrate that energy at the macroscopic scale can be accounted for as a combination of energy associated with the motion of particles and energy associated with the relative position of particles.",
        clarification: "Examples of models could include diagrams, drawings, and thermal energy kinetic simulations.",
        boundary: "Assessment does not include quantitative calculations of specific particle states.",
        sep: "Developing and Using Models",
        dci: "PS3.A: Definitions of Energy",
        ccc: "Energy and Matter",
        unitLink: "../unit5-dashboard.html",
        keywords: ["microscopic", "thermodynamics", "temperature", "heat", "particle motion", "kinetic theory"]
    },
    {
        code: "HS-PS3-3",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Energy",
        title: "Thermal Energy Device Engineering Design",
        pe: "Design, build, and refine a device that works within given constraints to convert one form of energy into another form of energy.",
        clarification: "Examples of devices could include solar cookers, thermal heat pumps, wind turbines, or rube goldberg mechanisms.",
        boundary: "Assessment is limited to relative efficiency comparisons.",
        sep: "Constructing Explanations and Designing Solutions",
        dci: "PS3.B: Conservation of Energy and Energy Transfer",
        ccc: "Energy and Matter",
        unitLink: "../unit5-dashboard.html",
        keywords: ["energy conversion", "heat pump", "thermal device", "efficiency", "generator", "solar"]
    },
    {
        code: "HS-PS3-4",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Energy",
        title: "Second Law of Thermodynamics & Thermal Equilibrium",
        pe: "Plan and conduct an investigation to provide evidence that the transfer of thermal energy when two components of different temperature are combined within a closed system results in a more uniform energy distribution.",
        clarification: "Emphasis is on thermal equilibrium, calorimetry, and heat flow direction.",
        boundary: "Assessment does not include calculations of entropy changes.",
        sep: "Planning and Carrying Out Investigations",
        dci: "PS3.B: Conservation of Energy and Energy Transfer",
        ccc: "Systems and System Models",
        unitLink: "../unit5-dashboard.html",
        keywords: ["thermodynamics", "thermal equilibrium", "heat transfer", "conduction", "calorimetry", "entropy"]
    },

    // --- PHYSICAL SCIENCE: WAVES & EM RADIATION (HS-PS4) ---
    {
        code: "HS-PS4-1",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Waves & EM Radiation",
        title: "Wave Speed, Frequency, and Wavelength Equation",
        pe: "Use mathematical representations to support a claim regarding relationships among the frequency, wavelength, and speed of waves traveling in various media.",
        clarification: "Emphasis is on the wave equation (v = f * λ) and qualitative wave properties across electromagnetic and mechanical spectrums.",
        boundary: "Assessment is limited to algebraic relationships.",
        sep: "Using Mathematics and Computational Thinking",
        dci: "PS4.A: Wave Properties",
        ccc: "Cause and Effect",
        unitLink: "../unit6-dashboard.html",
        keywords: ["wave equation", "v=f*lambda", "frequency", "wavelength", "wave speed", "sound", "light"]
    },
    {
        code: "HS-PS4-2",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Waves & EM Radiation",
        title: "Digital Transmission & Wave Encoding",
        pe: "Evaluate questions about the advantages of using a digital transmission and storage of information over an analog wave format.",
        clarification: "Emphasis is on pulse binary signals, noise immunity, storage efficiency, and clear signal transmission.",
        boundary: "Assessment does not include binary code conversion calculations.",
        sep: "Asking Questions and Defining Problems",
        dci: "PS4.A: Wave Properties",
        ccc: "Structure and Function",
        unitLink: "../unit6-dashboard.html",
        keywords: ["digital", "analog", "signals", "transmission", "telecommunication", "binary", "noise"]
    },
    {
        code: "HS-PS4-3",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Waves & EM Radiation",
        title: "Wave-Particle Duality & Electromagnetic Radiation",
        pe: "Evaluate the claims, evidence, and reasoning behind the idea that electromagnetic radiation can be described either by a wave model or a particle model.",
        clarification: "Emphasis is on photoelectric effect, interference patterns, and spectral lines.",
        boundary: "Assessment does not include quantum mechanics mathematics.",
        sep: "Engaging in Argument from Evidence",
        dci: "PS4.B: Electromagnetic Radiation",
        ccc: "Systems and System Models",
        unitLink: "../unit6-dashboard.html",
        keywords: ["wave particle duality", "photon", "photoelectric effect", "light", "spectrum", "quantum"]
    },
    {
        code: "HS-PS4-4",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Waves & EM Radiation",
        title: "EM Radiation Absorption & Material Interaction",
        pe: "Evaluate the validity and reliability of claims in published materials of the effects that different frequencies of electromagnetic radiation have when absorbed by matter.",
        clarification: "Emphasis is on the relationship between photon energy (E = hf) and ionization potential (UV, X-rays, Gamma vs. radio/visible).",
        boundary: "Assessment is limited to qualitative absorption effects.",
        sep: "Obtaining, Evaluating, and Communicating Information",
        dci: "PS4.B: Electromagnetic Radiation",
        ccc: "Cause and Effect",
        unitLink: "../unit6-dashboard.html",
        keywords: ["em spectrum", "radiation", "absorption", "uv light", "x-ray", "photon energy", "health"]
    },
    {
        code: "HS-PS4-5",
        domain: "Physical Science",
        domainCode: "PS",
        topic: "Waves & EM Radiation",
        title: "Wave Technology Devices in Society",
        pe: "Communicate technical information about how some technological devices use the principles of wave behavior and wave interactions with matter to transmit and capture information and energy.",
        clarification: "Examples of devices could include medical imaging (MRI, ultrasound), solar cells, fiber optics, and RFID.",
        boundary: "Assessment does not include circuit schematics or device physics equations.",
        sep: "Obtaining, Evaluating, and Communicating Information",
        dci: "PS4.C: Information Technologies and Instrumentation",
        ccc: "Structure and Function",
        unitLink: "../unit6-dashboard.html",
        keywords: ["wave technology", "mri", "fiber optics", "ultrasound", "sonar", "telemetry", "instruments"]
    },

    // --- EARTH & SPACE SCIENCE: EARTH'S PLACE IN UNIVERSE (HS-ESS1) ---
    {
        code: "HS-ESS1-1",
        domain: "Earth & Space Science",
        domainCode: "ESS",
        topic: "Earth's Place in Universe",
        title: "Nuclear Fusion in Stars & Stellar Evolution",
        pe: "Develop a model based on evidence to illustrate the life span of the sun and the role of nuclear fusion in the sun's core to release energy that eventually reaches Earth in the form of radiation.",
        clarification: "Emphasis is on H-R diagrams, stellar mass, nuclear fusion (H to He), and radiative/convective transport.",
        boundary: "Assessment does not include details of nuclear reaction cross-sections.",
        sep: "Developing and Using Models",
        dci: "ESS1.A: The Universe and Its Stars",
        ccc: "Scale, Proportion, and Quantity",
        unitLink: "../Unit_6_Waves_Radiation/The_Big_Bang/Hubbles_Law.html",
        keywords: ["sun", "fusion", "stars", "stellar evolution", "hr diagram", "solar energy", "hydrogen"]
    },
    {
        code: "HS-ESS1-2",
        domain: "Earth & Space Science",
        domainCode: "ESS",
        topic: "Earth's Place in Universe",
        title: "Big Bang Theory & Cosmic Expansion",
        pe: "Construct an explanation of the Big Bang theory based on astronomical evidence of light spectra, motion of distant galaxies, and composition of matter in the universe.",
        clarification: "Emphasis is on Doppler redshift of distant galaxy spectra, Cosmic Microwave Background Radiation (CMBR), and hydrogen/helium abundance.",
        boundary: "Assessment does not include general relativity equations.",
        sep: "Constructing Explanations and Designing Solutions",
        dci: "ESS1.A: The Universe and Its Stars",
        ccc: "Energy and Matter",
        unitLink: "../Unit_6_Waves_Radiation/The_Big_Bang/Hubbles_Law.html",
        keywords: ["big bang", "redshift", "hubble law", "cmbr", "cosmology", "universe expansion", "spectra"]
    },
    {
        code: "HS-ESS1-3",
        domain: "Earth & Space Science",
        domainCode: "ESS",
        topic: "Earth's Place in Universe",
        title: "Stellar Nucleosynthesis of Heavy Elements",
        pe: "Communicate scientific ideas about how stars produce elements through nuclear fusion over their life cycle.",
        clarification: "Emphasis is on elements up to iron formed in main sequence/giant stars, and elements heavier than iron forged during supernova explosions.",
        boundary: "Assessment does not include specific isotopic decay series calculations.",
        sep: "Obtaining, Evaluating, and Communicating Information",
        dci: "ESS1.A: The Universe and Its Stars",
        ccc: "Energy and Matter",
        unitLink: "../Unit_6_Waves_Radiation/The_Big_Bang/Hubbles_Law.html",
        keywords: ["nucleosynthesis", "supernova", "elements", "iron", "heavy elements", "star life cycle"]
    },
    {
        code: "HS-ESS1-4",
        domain: "Earth & Space Science",
        domainCode: "ESS",
        topic: "Earth's Place in Universe",
        title: "Kepler's Laws of Planetary Motion",
        pe: "Use mathematical or computational representations to predict the motion of orbiting objects in the solar system.",
        clarification: "Emphasis is on Kepler's 3 Laws of Planetary Motion (elliptical orbits, equal areas in equal times, $T^2 \\propto a^3$).",
        boundary: "Assessment does not include multi-body perturbation calculations.",
        sep: "Using Mathematics and Computational Thinking",
        dci: "ESS1.B: Earth and the Solar System",
        ccc: "Scale, Proportion, and Quantity",
        unitLink: "../comet-simulator/index.html",
        keywords: ["kepler laws", "orbits", "planets", "eccentricity", "orbital period", "gravity", "ellipse"]
    },

    // --- EARTH & SPACE SCIENCE: EARTH'S SYSTEMS (HS-ESS2) ---
    {
        code: "HS-ESS2-1",
        domain: "Earth & Space Science",
        domainCode: "ESS",
        topic: "Earth's Systems",
        title: "Plate Tectonics & Internal Heat Convection",
        pe: "Develop a model to illustrate how Earth's internal and surface processes operate at different spatial and temporal scales to form continental and ocean-floor features.",
        clarification: "Emphasis is on mantle convection currents, seafloor spreading, mountain building, and oceanic trench subduction zones.",
        boundary: "Assessment does not include memorization of specific geographic fault names.",
        sep: "Developing and Using Models",
        dci: "ESS2.A: Earth Materials and Systems",
        ccc: "Stability and Change",
        unitLink: "../2026-2027_Planning/Content_Review_For_CAST/Tectonic_Plate_Globe/index.html",
        keywords: ["plate tectonics", "mantle convection", "subduction", "seafloor spreading", "earthquakes", "crust"]
    },
    {
        code: "HS-ESS2-3",
        domain: "Earth & Space Science",
        domainCode: "ESS",
        topic: "Earth's Systems",
        title: "Earth's Interior Structure & Seismic Waves",
        pe: "Develop a model based on evidence of Earth's interior to describe the cycling of matter by thermal convection.",
        clarification: "Emphasis is on P-wave and S-wave shadow zones, liquid outer core, solid inner core, and density layering.",
        boundary: "Assessment does not include complex wave refraction Snell's law calculations for Earth core layers.",
        sep: "Developing and Using Models",
        dci: "ESS2.A: Earth Materials and Systems",
        ccc: "Energy and Matter",
        unitLink: "../2026-2027_Planning/Integrated_CAST_Prep.md",
        keywords: ["seismic waves", "p-waves", "s-waves", "earth interior", "core", "mantle", "shadow zone"]
    },

    // --- LIFE SCIENCE: ECOSYSTEMS & MOLECULES (HS-LS1 & HS-LS2) ---
    {
        code: "HS-LS1-5",
        domain: "Life Science",
        domainCode: "LS",
        topic: "From Molecules to Organisms",
        title: "Photosynthesis & Chemical Energy Storage",
        pe: "Use a model to illustrate how photosynthesis transforms light energy into stored chemical energy.",
        clarification: "Emphasis is on the overall reaction ($6CO_2 + 6H_2O \\rightarrow C_6H_{12}O_6 + 6O_2$) and chloroplast energy conversion.",
        boundary: "Assessment does not include biochemical details of ATP synthase or Krebs cycle pathways.",
        sep: "Developing and Using Models",
        dci: "LS1.C: Organization for Matter and Energy Flow in Organisms",
        ccc: "Energy and Matter",
        unitLink: "../Data_Analysis/index.html",
        keywords: ["photosynthesis", "glucose", "chloroplast", "light energy", "chemical energy", "carbon dioxide"]
    },
    {
        code: "HS-LS2-4",
        domain: "Life Science",
        domainCode: "LS",
        topic: "Ecosystems",
        title: "Trophic Levels & Biomass Energy Pyramids",
        pe: "Use mathematical representations to support claims for the cycling of matter and flow of energy among organisms in an ecosystem.",
        clarification: "Emphasis is on the 10% energy transfer rule between trophic levels (producers, primary/secondary consumers).",
        boundary: "Assessment is limited to basic trophic calculations.",
        sep: "Using Mathematics and Computational Thinking",
        dci: "LS2.B: Cycles of Matter and Energy Transfer in Ecosystems",
        ccc: "Energy and Matter",
        unitLink: "../Data_Analysis/index.html",
        keywords: ["trophic level", "biomass", "energy pyramid", "ecosystem", "food web", "producers", "consumers"]
    },

    // --- ENGINEERING DESIGN (HS-ETS1) ---
    {
        code: "HS-ETS1-1",
        domain: "Engineering Design",
        domainCode: "ETS",
        topic: "Engineering Design",
        title: "Engineering Problem Criteria & Constraints",
        pe: "Analyze a major global challenge to specify qualitative and quantitative criteria and constraints for solutions that account for societal needs and wants.",
        clarification: "Emphasis is on defining clear engineering requirements, economic constraints, and safety tolerances.",
        boundary: "Assessment is limited to qualitative problem formulation.",
        sep: "Asking Questions and Defining Problems",
        dci: "ETS1.A: Defining and Delimiting Engineering Problems",
        ccc: "Influence of Engineering, Technology, and Science on Society",
        unitLink: "../unit4-dashboard.html",
        keywords: ["engineering", "criteria", "constraints", "trade-offs", "problem definition", "design"]
    },
    {
        code: "HS-ETS1-2",
        domain: "Engineering Design",
        domainCode: "ETS",
        topic: "Engineering Design",
        title: "Designing & Evaluating Complex Engineering Solutions",
        pe: "Design a solution to a complex real-world problem by breaking it down into smaller, more manageable problems that can be solved through engineering.",
        clarification: "Examples of problems could include renewable energy grids, water filtration, or crash safety.",
        boundary: "Assessment is limited to system decomposition strategies.",
        sep: "Constructing Explanations and Designing Solutions",
        dci: "ETS1.B: Developing Possible Solutions",
        ccc: "Systems and System Models",
        unitLink: "../circuit-game.html",
        keywords: ["engineering design", "system decomposition", "prototyping", "solutions", "optimization"]
    },
    {
        code: "HS-ETS1-4",
        domain: "Engineering Design",
        domainCode: "ETS",
        topic: "Engineering Design",
        title: "Computer Modeling & Trade-off Optimization",
        pe: "Use a computer simulation to model the impact of proposed solutions to a complex real-world problem with numerous criteria and constraints on interactions within and between systems relevant to the problem.",
        clarification: "Emphasis is on analyzing trade-offs, cost-benefit ratios, and parametric simulations.",
        boundary: "Assessment does not include coding custom simulation engines from scratch.",
        sep: "Using Mathematics and Computational Thinking",
        dci: "ETS1.B: Developing Possible Solutions",
        ccc: "Systems and System Models",
        unitLink: "../Data_Analysis/index.html",
        keywords: ["simulation", "modeling", "computer model", "trade-off", "optimization", "params"]
    }
];

if (typeof window !== 'undefined') {
    window.NGSS_STANDARDS_DATA = NGSS_STANDARDS_DATA;
}
